#!/usr/bin/env php 
<?php

use App\Core\Config;
use Symfony\Component\Console\Application;

$container = require __DIR__ . '/bootstrap.php';

$config = $container->get(Config::class);

$application = new Application($config->get('app_name'), $config->get('app_version'));

$listCommands = require CONFIG_PATH . '/commands.php';

$application->addCommands(
    commands: array_map(callback: fn($command): mixed
        => $container->get($command), array: $listCommands)
);

$application->run();
